base:
  seed: 1
  num_workers: 6

wandb:
  name: 'disable_tfr'
  project: 'DLPLAB4'
  entity: 'kyoyachuan' 

data:
  data_root: '/home/kyoyachuan/mindrope/data'
  n_past: 2
  n_future: 10
  sliding_window: true
  batch_size: 12

model:
  model_path: '/home/kyoyachuan/mindrope/save_models/disable_tfr.pth'
  cond_convolution: false
  learned_prior: false
  prior_rnn_layers: 1
  rnn_size: 256
  posterior_rnn_layers: 1
  predictor_rnn_layers: 2
  z_dim: 64
  g_dim: 128
  last_frame_skip: true
  first_frame_skip: false

trainer:
  niters: 300
  epoch_size: 600
  lr: 0.002
  kl_anneal_cyclical: true
  kl_anneal_ratio: 0.5
  kl_anneal_cycle: 3
  tfr: 0.0
  tfr_start_decay_epoch: 100
  tfr_decay_step: 0.003
  tfr_lower_bound: 0.0
  evaluate_interval: 5
